#!/usr/bin/env bash
case $1 in
p | puma)
echo puma server
sshpass -p kalengo2go_p ssh -o PubkeyAuthentication=no -p 2208 klg@puma.local
;;
a1 | aliyun1)
echo aliyun server
sshpass -p klg2goklg2go ssh -p 2208 klg@112.74.207.91
;;
a2 | aliyun2)
echo aliyun2 server
sshpass -p klg2goklg2go ssh -p 2208 klg@120.25.14.185
;;
a3 | aliyun3)
echo aliyun3 server
sshpass -p klg2goklg2go ssh -p 2208 klg@120.76.76.170
;;
a4 | aliyun4)
echo aliyun4 server
sshpass -p klg2goklg2go ssh -p 2208 klg@120.76.24.92
;;
l | lion)
echo lion server
sshpass -p kalengo_koala_@l ssh -p 2208 -o PubkeyAuthentication=no klg@lion.prod.kalengo.cn
;;
b | butterfly)
echo butterfly server
sshpass -p kalengo_koala_@b ssh -o PubkeyAuthentication=no -p 2208 klg@butterfly.local
;;
g | gento)
echo gento server
sshpass -p kalengo_koala@g ssh -o PubkeyAuthentication=no -p 2208 klg@14.17.103.13
;;
d | dolphin)
echo dolphin server
sshpass -p kalengo_koala_@d ssh -p 2208 klg@dolphin.local
;;
o | opensocial)
echo local opensocial server
sshpass -p Kalengo2go ssh root@opensocial
;;
y | yammer)
echo local yammer server
sshpass -p kalengo ssh rain@yammer
;;
k | koala)
echo local koala server
sshpass -p klg2go ssh -o PubkeyAuthentication=no klg@koala
;;
t | tiger)
echo tiger
sshpass -p klg2go_kaola@_t ssh klg@tiger.prod.kalengo.cn 
;;
s | leo)
echo local leo server
sshpass -p kalengo2go ssh leo@192.168.1.14
;;
ben)
echo local ben server
sshpass -p chenlinben ssh ben@192.168.1.54
;;
*)
echo dolphin 
sshpass -p kalengo_bau1024_d ssh klg@dolphin.prod.kalengo.cn
;;
esac

